name: CI
on:
  pull_request:

# Cancel in-progress runs for pull requests when developers push new changes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  test-terraform:
    name: Validate Terraform output
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Detect changed files
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          list-files: shell
          filters: |
            shared:
              - 'test/**'
              - 'package.json'
              - 'bun.lock'
              - 'bunfig.toml'
              - 'tsconfig.json'
              - '.github/workflows/ci.yaml'
              - 'scripts/ts_test_auto.sh'
              - 'scripts/terraform_test_all.sh'
              - 'scripts/terraform_validate.sh'
              - 'scripts/shellcheck_validate.sh'
            modules:
              - 'registry/**/modules/**'
            templates:
              - 'registry/**/templates/**'
            shell:
              - '**/*.sh'
            all:
              - '**'
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false
      - name: Set up Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          # We're using the latest version of Bun for now, but it might be worth
          # reconsidering. They've pushed breaking changes in patch releases
          # that have broken our CI.
          # Our PR where issues started to pop up: https://github.com/coder/modules/pull/383
          # The Bun PR that broke things: https://github.com/oven-sh/bun/pull/16067
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run TypeScript tests
        env:
          ALL_CHANGED_FILES: ${{ steps.filter.outputs.all_files }}
          SHARED_CHANGED: ${{ steps.filter.outputs.shared }}
          MODULE_CHANGED_FILES: ${{ steps.filter.outputs.modules_files }}
        run: bun run check:typescript
      - name: Run Terraform tests
        env:
          ALL_CHANGED_FILES: ${{ steps.filter.outputs.all_files }}
          SHARED_CHANGED: ${{ steps.filter.outputs.shared }}
          MODULE_CHANGED_FILES: ${{ steps.filter.outputs.modules_files }}
        run: bun run check:terraform
      - name: Run Terraform Validate
        env:
          ALL_CHANGED_FILES: ${{ steps.filter.outputs.all_files }}
          SHARED_CHANGED: ${{ steps.filter.outputs.shared }}
          MODULE_CHANGED_FILES: ${{ steps.filter.outputs.modules_files }}
          TEMPLATE_CHANGED_FILES: ${{ steps.filter.outputs.templates_files }}
        run: bun run check:validate
      - name: Run ShellCheck
        env:
          ALL_CHANGED_FILES: ${{ steps.filter.outputs.all_files }}
          SHARED_CHANGED: ${{ steps.filter.outputs.shared }}
          SHELL_CHANGED_FILES: ${{ steps.filter.outputs.shell_files }}
        run: bun run check:shellcheck
      - name: Validate set -u ordering
        run: ./scripts/validate_set_u_order.sh
  validate-style:
    name: Check for typos and unformatted code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest
      # Need Terraform for its formatter
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false
      - name: Install dependencies
        run: bun install
      - name: Validate formatting
        run: bun fmt:ci
      - name: Check for typos
        uses: crate-ci/typos@4d9c206a77c041268485162b8e2579ad7a5cb9a3 # v1.50.0
        with:
          config: .github/typos.toml
  validate-readme-files:
    name: Validate README files
    runs-on: ubuntu-latest
    # We want to do some basic README checks first before we try analyzing the
    # contents
    needs: validate-style
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Validate contributors
        run: go build ./cmd/readmevalidation && ./readmevalidation
      - name: Remove build file artifact
        run: rm ./readmevalidation
